### ISSUE TITLE
JSON switch should output file in .json

### ISSUE THREAD

**Issue by brajjan** [MScholtes/Firewall-Manager#1]
Thank you for this great module!
Currently the json parameter does not export the file as .json but as a .csv -file. Would be great if it changed the extention

**Comment by MScholtes** [comment]
Hello brajjan,

you're correct, that's no proper code. I will overwork the code soon, please use parameter -CSVFile to specify name and extension of json file until then.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello brajjan,

released version 1.0.3 that solves the issue.

Greetings

Markus

**Comment by MScholtes** [comment]
Issue closed because there was no reaction for over three weeks.
